{% set version = "0.0.9" %}
{% set python_min = "3.6" %}

package:
  name: modestpy
  version: {{ version }}

source:
  fn: modest-py-v.{{ version }}.tar.gz
  url: https://github.com/sdu-cfei/modest-py/archive/v.{{ version }}.tar.gz
  sha256: cb88a8d1fac906f53169aacd66aec2d49fb01b78b4db1c79656b371ad70bea27

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - scipy
    - pandas
    - matplotlib-base
    - pydoe
    - pyfmi

test:
  requires:
    - python {{ python_min }}
  imports:
    - modestpy
    - modestpy.estim
    - modestpy.estim.ga
    - modestpy.estim.ps
    - modestpy.estim.scipy
    - modestpy.fmi
    - modestpy.utilities

about:
  home: https://github.com/sdu-cfei/modest-py
  license: BSD-2-Clause
  license_file: LICENSE
  summary: FMI-compliant Model Estimation in Python

extra:
  recipe-maintainers:
    - jschueller
    - krzysztofarendt
