travis:
  secure:
    BINSTAR_TOKEN: QzY741/DqF5tt1JyD0QRhB7m5tehZuLMBdh4OQI4pgJDqr+mL7QhuJaPGtBaZci9cq/JNqV2Uw4DTCrWNcVzK7KWaegGqmmmLsZH0ELapX6fTyjhVa5cIO8j5zjaI5BIriSrGsv6Jh3i3QREJvHFnBHcQrhzwWqlahDyT3+wmcipcQXW70PEPFhGKErmM4Ox1zc5lVrxKUpRiOodDX1nXLZjawapbJ9vra0Ci0dm0foyYB1Vma+U0yFN7ysY0u0489b4OK2XACvQnuib066QnzVtjh8Bxl1reDzVxc2u6NILy0KryAe9WB8X5r6WpoOUO/pOvSTpiQaDScSCMSKDpN7wRj2VQXN4zrOQF2rzp5m0k2X9NKWdaDLLs0513xRywxQX88Jv7H7f8TSZc8NjkxpstL+VO+QSgJUIJZ0lEY0+amkCN0JY50udCm9/9pVQ5ydauCIW6hQddZXVSDKpJnzz9E6ksSY0E1GAAXK8QPW1mpf/yfA5lYQsLEEaesDGw16bChhsviYfa42XbRxuRh3rg+NprpdJFe2Y+8AHxutDm04PYsgvwq6rdfl11VavcOSyNfioHPSj1IQL6A6G9c4Q0Wc7esik9fcOfWICPO8SV3eWsw0/67FY+A5gj673UtyuWFZRKbp47rA0voXg7z/zYNefKZBFLbXG87R9TDM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
